import type { DeliveryRow } from "./delivery-store.types";

const geo = { destinationLatitude: null, destinationLongitude: null, arrivalRadiusKm: 0.5 };

export const seedDeliveries: DeliveryRow[] = [
  { id: "TF-2841", customer: "Atlas Home", destination: "Casablanca, MA", ...geo, truck: "TRK-014", driver: "Youssef B.", status: "In transit", eta: "19 Aug · 14:00–18:00", progress: 68, color: "#16a272", contact: "", sendatrackVehicleId: "", latitude: null, longitude: null, speed: null, lastPositionAt: null, gpsSource: "simulation", companyId: "demo", trackingToken: null, createdAt: new Date("2026-08-14T08:42:00Z") },
  { id: "TF-2839", customer: "Medina Import", destination: "Tangier, MA", ...geo, truck: "TRK-007", driver: "Sophie L.", status: "Delayed", eta: "20 Aug · 09:00–13:00", progress: 55, color: "#f1a43c", contact: "", sendatrackVehicleId: "", latitude: null, longitude: null, speed: null, lastPositionAt: null, gpsSource: "simulation", companyId: "demo", trackingToken: null, createdAt: new Date("2026-08-14T08:35:00Z") },
  { id: "TF-2837", customer: "Brussels Parts", destination: "Brussels, BE", ...geo, truck: "TRK-019", driver: "Amine R.", status: "In transit", eta: "18 Aug · 16:00–20:00", progress: 82, color: "#4776e6", contact: "", sendatrackVehicleId: "", latitude: null, longitude: null, speed: null, lastPositionAt: null, gpsSource: "simulation", companyId: "demo", trackingToken: null, createdAt: new Date("2026-08-14T08:22:00Z") },
  { id: "TF-2835", customer: "Rif Logistics", destination: "Antwerp, BE", ...geo, truck: "TRK-003", driver: "Nora V.", status: "Loading", eta: "21 Aug · 10:00–14:00", progress: 8, color: "#916ed7", contact: "", sendatrackVehicleId: "", latitude: null, longitude: null, speed: null, lastPositionAt: null, gpsSource: "simulation", companyId: "demo", trackingToken: null, createdAt: new Date("2026-08-14T08:10:00Z") },
  { id: "TF-2832", customer: "EuroMaghreb", destination: "Liège, BE", ...geo, truck: "TRK-011", driver: "Marc D.", status: "Delivered", eta: "17 Aug · 17:32", progress: 100, color: "#6b7280", contact: "", sendatrackVehicleId: "", latitude: null, longitude: null, speed: null, lastPositionAt: null, gpsSource: "simulation", companyId: "demo", trackingToken: null, createdAt: new Date("2026-08-14T07:50:00Z") },
];
